name: MOPS Daily Monitor

on:
  schedule:
    - cron: '0 10,13 * * *' # 台灣 18:00 與 21:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升級版本

      - name: Set up Python
        uses: actions/setup-python@v5 # 升級版本
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python monitor.py